version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USERNAME=payment
      - POSTGRES_PASSWORD=payment
    ports:
      - 5432:5432
    volumes:
      - data-volume:/var/lib/db
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  data-volume:
