version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USERNAME=payment
      - POSTGRES_PASSWORD=payment
    ports:
      - 5432:5432
    volumes:
      - data-volume:/var/lib/db

volumes:
  data-volume:
